[package]
name = "oxifoc-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
ergot = { path = "../ergot/crates/ergot" }
postcard-schema = { version = "0.2.5", features = ["derive"] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
